### PR TITLE
Hw1

### PR DESCRIPTION
**Pull request by OcheretnyArtem**

### CODE REVIEW

**Comment by OcheretnyArtem** [comment]
я зделяль

**Review by Berikz80 — APPROVED** [review]

**Review by Berikz80 — APPROVED** [review]

**Review by YarikGuk — APPROVED** [review]
Nice job!

**Review by e-kleban — APPROVED** [review]
good job, cool colors)

**Review by Gizcerbes — APPROVED** [review]

**Comment by baranovdev** [comment]
**hey,bro**
nice code, awesome brackets

**Pull request merged**
